# Generated by Django 4.2.5 on 2023-10-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_alter_payment_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма оплаты'),
        ),
    ]
